<?php

use Illuminate\Database\Seeder;
use App\Milestone;

class MilestonesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $hitos = [
            ['1.1.1',     '1.1',  'Disponer la implementación del EGSI en la institución por la máxima autoridad.', true],
            ['1.1.2',     '1.1',  'Difundir la política de seguridad de la información de referencia o propia de la institución.', true],
            ['1.2.1',     '1.1',  'Garantizar la vigencia de la política de seguridad de la información en la institución.', true],
            ['2.1.1',     '2.1',  'Realizar el seguimiento de la puesta en marcha de las normas de este documento ', true],
            ['2.1.2',     '2.1',  'Disponer la difusión, capacitación y sensibilización del contenido de este documento ', true],
            ['2.1.3',     '2.1',  'Conformar oficialmente el Comité de Gestión de la Seguridad de la Información de la institución (CSI) y designar a los integrantes.', true],
            ['2.2.1.1',   '2.2',  'Designar formalmente a un funcionario como Oficial de Seguridad de la Información quien actuará como coordinador del CSI.', true],
            ['2.2.1.2',   '2.2',  'Designar formalmente al responsable de seguridad del área de Tecnologías de la Información.', true],
            ['2.5.1',     '2.5',  'Elaborar y aprobar los acuerdos de confidencialidad y de no-divulgación de información conforme la Constitución, las leyes, las necesidades de protección de información de la institución y el EGSI', true],
            ['2.5.2',     '2.5',  'Controlar que los acuerdos de confidencialidad de la información, documento físico o electrónico,  sean firmados de forma manuscrita o electrónica por todo el personal de la institución sin excepción', true],
            ['2.5.3',     '2.5',  'Gestionar la custodia de los acuerdos firmados, en los expedientes, físicos o electrónicos, de cada funcionario, por parte del área de gestión de recursos humanos', true],
            ['2.5.4',     '2.5',  'Controlar que la firma de los acuerdos de confidencialidad sean parte de los procedimientos de  incorporación de nuevos funcionarios a la institución, sin excepción', true],
            ['2.5.5',     '2.5',  'Gestionar la aceptación, entendimiento y firma de acuerdos de confidencialidad y de no divulgación de información por parte de terceros.', true],
            ['3.1.2.1',   '3.1',  'Equipos móviles: teléfono inteligente (smartphone), teléfono celular, tableta, computador portátil, asistente digital personal (PDA), etc.', true],
            ['3.1.2.2',   '3.1',  'Equipos fijos: servidor de torre, servidor de cuchilla, servidor de rack, computador de escritorio, computadoras portátiles, etc.', true],
            ['3.1.2.3',   '3.1',  'Periféricos de entrada: teclado, ratón, micrófono, escáner plano, escáner de mano, cámara digital, cámara web, lápiz óptico, pantalla de toque, etc.', true],
            ['3.1.2.4',   '3.1',  'Periféricos de salida: monitor, proyector, audífonos, parlantes, impresora láser, impresora de inyección de tinta, impresora matricial, impresora térmica, plóter, máquina de fax, etc.', true],
            ['3.1.2.5',   '3.1',  'Periféricos y dispositivos de almacenamiento: sistema de almacenamiento (NAS, SAN), librería de cintas, cintas magnéticas, disco duro portátil, disco flexible, grabador de discos (CD, DVD, Blu-ray), CD, DVD, Blu-ray,  memoria USB, etc.', true],
            ['3.1.2.6',   '3.1',  'Periféricos de comunicaciones: tarjeta USB para redes inalámbricas (Wi-Fi, Bluetooth, GPRS, HSDPA), tarjeta PCMCIA para redes inalámbricas (Wi-Fi, Bluetooth, GPRS, HSDPA), tarjeta USB para redes alámbricas/inalámbricas de datos y de telefonía, etc.', true],
            ['3.1.2.7',   '3.1',  'Tableros: de transferencia (bypass) de la unidad interrumpible de energía (UPS), de salidas de energía eléctrica, de transferencia automática de energía, etc.', true],
            ['3.1.2.8',   '3.1',  'Sistemas: de control de accesos, de aire acondicionado, automático de extinción de incendios, de circuito cerrado de televisión, etc.', true],
            ['3.1.3.1',   '3.1',  'Sistemas operativos', true],
            ['3.1.3.2',   '3.1',  'Software de servicio, mantenimiento o administración de: gabinetes de servidores de cuchilla, servidores (estantería/rack, torre, virtuales), sistema de redes de datos, sistemas de almacenamiento (NAS, SAN), telefonía, sistemas (de UPS, grupo electrógeno, de aire acondicionado, automático de extinción de incendios, de circuito cerrado de televisión), etc.', true],
            ['3.1.3.3',   '3.1',  'Paquetes de software o software base de: suite de ofimática, navegador de Internet, cliente de correo electrónico, mensajería instantánea, edición de imágenes, vídeo conferencia, servidor (proxy,  de archivos, de correo electrónico, de impresiones, de mensajería instantánea, de aplicaciones, de base de datos), etc.', true],
            ['3.1.3.4',   '3.1',  'Aplicativos informáticos del negocio', true],
            ['3.1.4.1',   '3.1',  'Cables de comunicaciones (interfaces: RJ-45 o RJ-11, SC, ST o MT-RJ,interfaz V35, RS232, USB, SCSI, LPT),  panel de conexión (patch panel), tomas o puntos de red, racks (cerrado o abierto, de piso o pared), etc.', true],
            ['3.1.4.2',   '3.1',  'Switchs (de centros de datos, de acceso, de borde, de gabinete de servidores, access-ppoint, transceiver, equipo terminal de datos, etc.).', true],
            ['3.1.4.3',   '3.1',  'Ruteador (router), cortafuego (firewall), controlador de red inalámbrica, etc.', true],
            ['3.1.4.4',   '3.1',  'Sistema de detección/prevención de intrusos (IDS/IPS), firewall de aplicaciones web, balanceador de carga, switch de contenido, etc.', true],
            ['3.3.1',     '3.3',  'Reglamentar el uso de correo electrónico institucional', true],
            ['3.3.2',     '3.3',  'Reglamentar el acceso y uso de la Internet y sus aplicaciones/servicios ', true],
            ['3.3.3',     '3.3',  'Reglamentar el uso de los sistemas de video-conferencia ', true],
            ['3.4.1',     '3.4',  'Clasificar la información como pública o confidencial', true],
            ['4.1.1',     '4.1',  'Verificar a los candidatos, previa su contratación, el certificado de antecedentes penales y revisar la información entregada en su hoja de vida ', true],
            ['4.1.2',     '4.1',  'Entregar formalmente a los funcionarios sus funciones y responsabilidades', true],
            ['4.4.1',     '4.4',  'Explicar y definir las funciones y las responsabilidades respecto a la seguridad de la información, antes de otorgar el acceso a la información, contraseñas o sistemas de información sensibles ', true],
            ['5.1.1',     '5.1',  'Definir una área de recepción, con personal y otros medios para controlar el acceso físico al lugar o edificio ', true],
            ['5.2.1',     '5.2',  'Supervisar la permanencia de los visitantes en las áreas restringidas y registrar la hora y fecha de su ingreso y salida ', true],
            ['5.2.2',     '5.2',  'Implementar el uso de una identificación  visible para todo el  personal y visitantes, quienes deberán ser escoltados por una persona autorizada para el tránsito en las  áreas restringidas ', true],
            ['5.3.1',     '5.3',  'Proteger las  instalaciones claves de tal manera que se evite el acceso al público ', true],
            ['5.3.2',     '5.3',  'Ubicar las impresoras, copiadoras, etc., en un área protegida', true],
            ['5.4.1',     '5.4',  'Realizar mantenimientos de las instalaciones eléctricas y UPS', true],
            ['5.4.2',     '5.4',  'Realizar mantenimientos en los sistemas de climatización y ductos de ventilación ', true],
            ['5.5.1',     '5.5',  'No permitir equipos de grabación, cámaras, equipos de vídeo y audio, dispositivos móviles, etc., a menos de que estén autorizados ', true],
            ['5.6.1',     '5.6',  'Permitir  el acceso al área de despacho y carga, únicamente a personal identificado y autorizado ', true],
            ['5.7.1',     '5.7',  'Establecer directrices para no comer, beber y fumar en las cercanías de las áreas de procesamiento de información ', true],
            ['5.8.1',     '5.8',  'Tener un sistema de suministro de energía sin interrupción (UPS) o al menos permitir el cierre/apagado ordenado de los servicios y equipos que soportan las operaciones críticas de los servicios informáticos de la institución ', true],
            ['5.9.1',     '5.9',  'Disponer de documentación, diseños/planos y la distribución de conexiones de: datos alámbricas/inalámbricas (locales y remotas), voz, eléctricas polarizadas, etc.', true],
            ['6.1.1',     '6.1',  'Documentar los contactos de soporte, necesarios en caso de incidentes ', true],
            ['6.6.1',     '6.6',  'Monitorear los niveles de desempeño de los servicios para verificar el cumplimiento de los acuerdos ', true],
            ['6.6.2',     '6.6',  'Analizar los reportes de servicios, reportes de incidentes elaborados por terceros y acordar reuniones periódicas según los acuerdos ', true],
            ['6.6.3',     '6.6',  'Revisar y verificar los registros y pruebas de auditoría de terceros, con respecto a eventos de seguridad, problemas de operación, fallas relacionados con el servicio prestado ', true],
            ['6.8.1',     '6.8',  'Realizar proyecciones de los requerimientos de capacidad futura de recursos para asegurar el desempeño de los servicios y sistemas informáticos ', true],
            ['6.10.1',    '6.10', 'Prohibir el uso de software no autorizado por la institución. Elaborar un listado del software autorizado', true],
            ['6.10.2',    '6.10', 'Instalar y actualizar periódicamente software de antivirus y contra código malicioso ', true],
            ['6.10.3',    '6.10', 'Mantener los sistemas operativos y sistemas de procesamiento de información actualizados con las últimas versiones de seguridad disponibles ', true],
            ['6.12.1',    '6.12', 'Los responsables del área de Tecnologías de la Información, Oficial de Seguridad de la Información junto con el propietario de la información, determinarán los procedimientos para el resguardo y contención de la información.', true],
            ['6.12.2',    '6.12', 'Definir el procedimiento de etiquetado de las copias de respaldo, identificando su contenido, periodicidad y retención ', true],
            ['6.12.3',    '6.12', 'Definir la extensión (completo/diferencial) y la frecuencia de los respaldos, de acuerdo a los requisitos del negocio de la institución ', true],
            ['6.14.1',    '6.14', 'Incorporar tecnología  para la seguridad de los servicios de red como la autenticación, encriptación y controles de conexión de red ', true],
            ['6.14.2',    '6.14', 'Implementar soluciones que proporcionen valor agregado a las conexiones y servicios de red,  como la implementación de firewalls, antivirus, etc.', true],
            ['6.26.1',    '6.26', 'Registrar los accesos y tipos de acceso ', true],
            ['6.26.2',    '6.26', 'Registrar las direcciones y protocolos de red ', true],
            ['6.26.3',    '6.26', 'Definir alarmas originadas por el sistema de control de acceso', true],
            ['6.26.4',    '6.26', 'Activación y desactivación de los sistemas de protección como antivirus y los sistemas de detección de intrusos (IDS) ', true],
            ['6.27.1',    '6.27', 'Registrar los accesos autorizados, incluyendo', true],
            ['6.27.2',    '6.27', 'Monitorear las operaciones privilegiadas', true],
            ['6.27.3',    '6.27', 'Monitorear intentos de acceso no autorizados', true],
            ['6.27.4',    '6.27', 'Revisar alertas o fallas del sistema', true],
            ['6.29.1',    '6.29', 'Registrar la hora en la que ocurrió el evento ', true],
            ['6.29.2',    '6.29', 'Registrar información sobre el evento ', true],
            ['6.29.3',    '6.29', 'Registrar la cuenta de administrador y operador que estuvo involucrado ', true],
            ['6.29.4',    '6.29', 'Registrar los procesos que estuvieron implicados ', true],
            ['6.30.1',    '6.30', 'Revisar los registros de fallas o errores del sistema ', true],
            ['6.30.2',    '6.30', 'Revisar las medidas correctivas para garantizar que no se hayan vulnerado los controles ', true],
            ['6.30.3',    '6.30', 'Asegurar que el registro de fallas esté habilitado ', true],
            ['7.4.1',     '7.4',  'Establecer un proceso formal para la asignación y cambio de contraseñas ', true],
            ['7.6.1',     '7.6',  'Documentar, en el procedimiento de accesos, las responsabilidades de los usuarios tanto internos como externos, sobre el uso de la cuenta y la contraseña asignados ', true],
            ['7.6.2',     '7.6',  'Recomendar la generación de contraseñas con letras mayúsculas, minúsculas, con caracteres especiales, difíciles de descifrar, es decir, que cumplen una complejidad media y alta ', true],
            ['7.6.3',     '7.6',  'Evitar contraseñas en blanco o que viene por defecto según el sistema el fabricante del producto, puesto que son fácilmente descifrables', true],
            ['7.6.4',     '7.6',  'Controlar el cambio periódico de contraseñas de los usuarios ', true],
            ['7.6.5',     '7.6',  'Generar y documentar revisiones periódicas de la gestión de usuarios incluidos los administradores de tecnología, por parte del Oficial de Seguridad  de la Información ', true],
            ['7.7.1',     '7.7',  'Implementar medidas para que, en un determinado tiempo (ej., no mayor a 10 minutos), si el usuario no está realizando ningún trabajo en el equipo, este se bloquee, y se desbloquee únicamente si el usuario ingresa nuevamente su clave ', true],
            ['7.8.1',     '7.8',  'Mantener bajo llave la información sensible (cajas fuertes o gabinetes), en especial cuando no estén en uso y no se encuentre personal en la oficina ', true],
            ['7.8.2',     '7.8',  'Desconectar de la red, servicio o sistema, las computadoras personales, terminales, impresoras asignadas a funciones críticas, cuando se encuentren desatendidas. Por ejemplo, haciendo uso de protectores de pantalla con clave ', true],
            ['7.8.3',     '7.8',  'Bloquear las copiadoras y disponer de un control de acceso especial para horario fuera de oficinas ', true],
            ['7.8.4',     '7.8',  'Retirar información sensible una vez que ha sido impresa ', true],
            ['7.8.5',     '7.8',  'Retirar información sensible, como las claves, de sus escritorios y pantallas ', true],
            ['7.8.6',     '7.8',  'Retirar los dispositivos removibles una vez que se hayan dejado de utilizar ', true],
            ['7.10.1',    '7.10', 'Generar mecanismos para asegurar la información transmitida por los canales de conexión remota, utilizando técnicas como encriptación de datos, implementación de redes privadas virtuales (VPN) y Servicio de Acceso Remoto (SAR) ', true],
            ['7.11.1',    '7.11', 'Identificar y documentar los equipos que se encuentran en las redes ', true],
            ['7.12.1',    '7.12', 'Los puertos, servicios (ej., fftp) que no se requieren por necesidades de la institución, deberán ser eliminados o deshabilitados ', true],
            ['7.13.1',    '7.13', 'Realizar una evaluación de riesgos para identificar los segmentos de red donde se encuentren los activos críticos para la institución ', true],
            ['7.15.1',    '7.15', 'Configurar políticas de control de acceso para el enrutamiento en la red, basándose en los requerimientos de la institución ', true],
            ['7.16.1',    '7.16', 'Autenticar usuarios autorizados, de acuerdo a la política de control de acceso de la institución, que deberá estar documentada, definida y socializada ', true],
            ['7.16.2',    '7.16', 'Llevar un registro de definición para el uso de privilegios especiales del sistema ', true],
            ['7.16.3',    '7.16', 'Llevar un proceso de monitoreo y registro de los intentos exitosos y fallidos de autenticación del sistema, registros de alarmas cuando se violan las políticas de seguridad del sistema ', true],
            ['7.16.4',    '7.16', 'Utilizar mecanismos como: uso de dominios de autenticación, servidores de control de acceso y directorios ', true],
            ['7.16.5',    '7.16', 'Restringir el tiempo de conexión de los usuarios, considerando las necesidades de la institución ', true],
            ['7.16.6',    '7.16', 'Controlar que no se muestren identificadores de aplicación ni de sistema, hasta que el proceso de registro de inicio se haya completado exitosamente', true],
            ['7.16.7',    '7.16', 'Limitar la cantidad de intentos permitidos de registro de inicio de sesión; por ejemplo, tres intentos ', true],
            ['7.16.8',    '7.16', 'Limitar el tiempo de dilación antes de permitir o rechazar más intentos adicionales del registro de inicio sin autorización específica ', true],
            ['7.17.1',    '7.17', 'Rastrear utilizando los identificadores de usuario y evidenciar las actividades de las personas responsables de administraciones críticas de la institución ', true],
            ['7.17.2',    '7.17', 'Usar como excepción, y solo por temas de necesidad de la institución, identificadores de usuarios para un grupo de usuarios o de trabajo específico, el cual debe estar definido y documentado ', true],
            ['7.17.3',    '7.17', 'Evitar el uso de usuarios genéricos ', true],
            ['7.17.4',    '7.17', 'Utilizar métodos alternos a la contraseña, como los medios criptográficos, las tarjetas inteligentes, tokens o medios biométricos de autenticación ', true],
            ['7.18.1',    '7.18', 'Evidenciar en la política de accesos, la responsabilidad del buen uso de la contraseña y que debe ser secreta e intransferible ', true],
            ['7.18.2',    '7.18', 'Controlar el cambio de contraseña de los usuarios y del personal de tecnología y de los administradores de tecnología, en rangos de tiempo y complejidad ', true],
            ['7.18.3',    '7.18', 'Forzar el cambio de contraseña en el primer registro de acceso o inicio de sesión ', true],
            ['7.25.1',    '7.25', 'Evitar exposición de equipos portátiles en sitios inseguros, públicos y de alto riesgo', true],
            ['7.26.1',    '7.26', 'No se permite el uso de equipo de propiedad privada que no esté bajo el control y monitoreo de la institución ', true],
            ['7.26.2',    '7.26', 'Deberá considerarse la protección de antivirus y reglas del Firewall ', true],
            ['8.1.1',     '8.1',  'Definir los requerimientos de seguridad. Por ejemplo: criptografía, control de sesiones, etc.', true],
            ['8.1.2',     '8.1',  'Definir los controles apropiados, tanto automatizados como manuales', true],
            ['9.1.1',     '9.1',  'Instaurar un procedimiento formal para el reporte de los eventos de seguridad de la información junto con un procedimiento de escalada y respuesta ante el incidente, que establezca la acción que se ha de tomar al recibir el reporte sobre un evento que amenace la seguridad de la información ', true],
            ['9.1.2',     '9.1',  'Cuando un incidente se produzca,  el funcionario en turno responsable del equipo o sistema afectado, debe realizar las siguientes acciones en su orden ', true],
            ['9.1.2.1',   '9.1',  'Identificar el incidente', true],
            ['9.1.2.2',   '9.1',  'Registrar el incidente en una bitácora de incidentes (reporte de eventos) incluyendo fecha, hora, nombres y apellidos del funcionario en turno, departamento o área afectada, equipo o sistema afectado y breve descripción del incidente', true],
            ['9.1.2.3',   '9.1',  'Notificar al Oficial de Seguridad de la Información de la institución', true],
            ['9.1.2.4',   '9.1',  'Clasificar el incidente de acuerdo al tipo de servicio afectado y al nivel de severidad', true],
            ['9.1.2.5',   '9.1',  'Asignar una prioridad de atención al incidente en el caso de que se produjeran varios en forma simultanea', true],
            ['9.1.2.6',   '9.1',  'Realizar un diagnóstico inicial, determinando mensajes de error producidos, identificando los eventos ejecutados antes de que el incidente ocurra, recreando el incidente para identificar sus posibles causas', true],
            ['9.1.2.7',   '9.1',  'Escalar el incidente en el caso que el funcionario en turno no pueda solucionarlo, el escalamiento deberá ser registrado en la bitácora de escalamiento de incidentes. El funcionario en turno debe escalar el incidente a su jefe inmediato, en el caso en el que el funcionario no tuviere un jefe al cual escalarlo, este debe solicitar soporte al proveedor del equipo o sistema afectado', true],
            ['9.1.2.8',   '9.1',  'Investigar y diagnosticar en forma definitiva las causas por las cuales se produjo el incidente', true],
            ['9.1.2.9',   '9.1',  'Resolver y restaurar el servicio afectado por el incidente debido a la para de un equipo o un sistema, incluyendo un registro de la solución empleada en la bitácora de incidentes', true],
            ['9.1.2.10',  '9.1',  'Cerrar el incidente, actualizando el estado del registro del incidente en la bitácora de incidentes a “Resuelto”. Confirmar con el funcionario en turno, responsable del equipo o del sistema de que el incidente ha sido resuelto', true],
        ];

        foreach ($hitos as $elem) {

            $hito = new Milestone;
            $hito->milestone_number = $elem[0];
            $hito->category_number = $elem[1];
            $hito->description = $elem[2];
            $hito->is_a_priority = $elem[3];

            $hito->save();
        }
    }
}
